### ISSUE TITLE
Add line tool to connect constraints

### ISSUE THREAD

**Issue by anickle060193** [anickle060193/vnaver#3]

**Comment by kellub** [comment]
Ensure that this supports level legs between constraints (or just use free-form lines) that can also snap to constraints).

**Comment by kellub** [comment]
Retain ability to add vertical lines since vertical lines without constraints represent legs with no traj pt(s).

**Comment by kellub** [comment]
Should this be re-opened until you can connect lines to lines as well?

**Comment by anickle060193** [comment]
Initial implementation added in b2f0890c5ffe10e689e98df53365980663ae8288.
